// Authentication
export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

// Projects
export const CREATE_PROJECT = "CREATE_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const GET_PROJECT = "GET_PROJECT";
export const PROJECT_LOADING = "PROJECT_LOADING";
export const GET_PROJECTS = "GET_PROJECTS";
export const PROJECTS_LOADING = "PROJECTS_LOADING";

// Home works
export const CREATE_HOMEWORK = "CREATE_HOMEWORK";
export const CREATE_HOMEWORK_LOADING = "CREATE_HOMEWORK_LOADING";
export const UPDATE_HOMEWORK = "UPDATE_HOMEWORK";
export const DELETE_HOMEWORK = "DELETE_HOMEWORK";
export const GET_HOMEWORK = "GET_HOMEWORK";
export const HOMEWORK_LOADING = "HOMEWORK_LOADING";
export const GET_HOMEWORKS = "GET_HOMEWORKS";
export const HOMEWORKS_LOADING = "HOMEWORKS_LOADING";

// Tasks
export const CREATE_TASK = "CREATE_TASK";
export const UPDATE_TASK = "UPDATE_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const GET_TASKS = "GET_TASKS";
export const TASKS_LOADING = "TASKS_LOADING";
